from building import *
import os
import glob

cwd = GetCurrentDir()

# --- 源码白名单 ---
src = [
    'mpp_pipeline/mpp_pipeline.c',
    'mpp_pipeline/vb_module.c',
    'mpp_pipeline/venc_module.c',
    'mpp_pipeline/vicap_module.c',
    'mpp_pipeline/bind_module.c',
    'mpp_pipeline/cleanup_module.c',
]

# --- MPP 头文件路径 ---
MPP_INC = '/home/ubuntu/k230_sdk/src/big/mpp'
CPPPATH = [
    cwd,
    os.path.join(MPP_INC, 'include'),
    os.path.join(MPP_INC, 'include/comm'),
    os.path.join(MPP_INC, 'include/ioctl'),
    os.path.join(MPP_INC, 'userapps/api'),
]

# --- MPP 静态库 ---
MPP_LIB_PATH = os.path.join(MPP_INC, 'userapps/lib')
lib_files = glob.glob(os.path.join(MPP_LIB_PATH, 'lib*.a'))
LIBS = [os.path.basename(f)[3:-2] for f in sorted(lib_files)]
LIBS += ['pthread', 'm']

LIBPATH = [MPP_LIB_PATH]

# --- 移除 -Werror (MPP 头文件 warning 不可控) ---
env = GetEnv()
old_flags = env.get('CCFLAGS', '')
new_flags = old_flags.replace('-Werror', '')
env.Replace(CCFLAGS=new_flags)

group = DefineGroup('big_app', src, depend=[''], CPPPATH=CPPPATH, LIBS=LIBS, LIBPATH=LIBPATH)
Return('group')
